### ISSUE TITLE
Get /vagrant shared folder working

### ISSUE THREAD

**Issue by mcandre** [b00ga/packer-templates#3]
Vagrant base boxes ideally provide a `/vagrant` mount as a sort of shared folder to the host directory. I attempted to configure shared folders on b00ga/dragonfly50 with `config.vm.synced_folder ".", "/vagrant", type: "rsync"`, but Vagrant reports that it is unable to have sufficient permission to create the `/vagrant` directory. In any case, the base box should set this up by default, so that downstream users don't have to spend time configuring this.

I also tried setting up shared folders via NFS, but it looks like the `configure_network` feature is lacking from the dragonfly box, and I don't know enough about Vagrant innards to add this capability to the box. For now, rsync is usually much easier to setup shared folders than NFS, looks like there's just a minor problem with UNIX permissions in that regard.

**Comment by b00ga** [comment]
Commit 2e8bedf addresses this issue by adding a script to create /vagrant and chown it vagrant:vagrant. Box release 0.1.1 for both DragonFly 4.8 & 5.0 released on Vagrant Cloud with this fix.

-Shawn

**Comment by mcandre** [comment]
Thanks for taking a look at this. I upgraded my Vagrantfile to use:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "b00ga/dragonfly50"
  config.vm.box_version = "0.1.1"
end
```

However, when I `vagrant ssh`, the /vagrant directory appears to be empty. For some reason, the files in my current working directory are not being mirrored into /vagrant. I'm not using any kind of vagrant excludes file or anything.

When I manually add the configuration `config.vm.synced_folder ".", "/vagrant", type: "rsync"` to my Vagrantfile, then /vagrant begins mirroring cwd. Could this configuration be moved into the base box, so that downstream users can automatically get /vagrant syncing by default?

**Comment by b00ga** [comment]
I didn't test with no synced folder specified (I specified to share "." on "/vagrant" with type "rsync"). According to the vagrant docs: 
type (string) - The type of synced folder. If this is not specified, Vagrant will automatically choose the best synced folder option for your environment. Otherwise, you can specify a specific type such as "nfs".
(ref: https://www.vagrantup.com/docs/synced-folders/basic_usage.html)

I'll try to dig through the vagrant source later, but it's quite possible that "rsync" is not the "best option" as far as vagrant is concerned for this box.

-Shawn

**Comment by b00ga** [comment]
From what I can tell from comparing output of a few different runs of vagrant with "--debug", NFS appears to be the default shared/synced folder type (I think for all BSD type boxes). This is part of the vagrant code, not something I can change as a box author.

-Shawn
